name: mybs
description: Bus Stop Lines
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  mybs_core_module:
    path: ../mybs_core_module
  mybs_db_module:
    path: ../mybs_db_module
  mybs_home_module:
    path: ../mybs_home_module
  # firebase_messaging:
  #   path: "./../flutterfire/packages/firebase_messaging/firebase_messaging"

  faker: ^2.0.0
  flutter_local_notifications: ^9.6.1
  firebase_core: ^1.19.1
  firebase_messaging: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.11

flutter:
  uses-material-design: true

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
